// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions']
    ADescriptionsItem: typeof import('ant-design-vue/es')['DescriptionsItem']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AResult: typeof import('ant-design-vue/es')['Result']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyText: typeof import('ant-design-vue/es')['TypographyText']
    ATypographyTitle: typeof import('ant-design-vue/es')['TypographyTitle']
    Bot: typeof import('./src/components/widget/card/Bot.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Grid: typeof import('./src/components/widget/Grid.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    Info: typeof import('./src/components/widget/card/Info.vue')['default']
    Load: typeof import('./src/components/widget/chart/Load.vue')['default']
    Main: typeof import('./src/components/layout/Main.vue')['default']
    Memory: typeof import('./src/components/widget/chart/Memory.vue')['default']
    NotFound: typeof import('./src/components/widget/NotFound.vue')['default']
    Tab: typeof import('./src/components/widget/card/Tab.vue')['default']
  }
}

export { }
