version: '3'
services:
  server:
    image: lifeni/monitor-server
    container_name: monitor-server
    restart: always
    networks:
      - network
    environment:
      DB_URL: postgresql://postgres:password@postgres:5432/node-monitor # 如有需要，可以修改
    ports:
      - 9010:9010 # WebSocket Port
      - 9020:9020 # HTTP Port
    depends_on:
      - postgres

  postgres:
    image: 'postgres'
    container_name: monitor-db
    restart: always
    networks:
      - network
    environment:
      POSTGRES_PASSWORD: password # 如果上面改了，这里也要改
    volumes:
      - data:/var/lib/postgres

networks:
  network:

volumes:
  data:
